### ISSUE TITLE
Unknown encoder 'libx264'

### ISSUE THREAD

**Issue by zeon** [magiclen/FFmpeg-For-MagicLen-Applications#1]
Hi I use this command which should work but it's not:

ffmpeg -i rtsp://0.tcp.ngrok.io:15082/stream.sdp1 -vcodec libx264 -vb 150000 -g 60 -vprofile baseline -level 2.1 -acodec aac -ab 64000 -ar 48000 -ac 2 -strict experimental -f mp4 /sdcard/a.mp4

The error says "Unknown encoder 'libx264'"

Did you support x264?

**Comment by magiclen** [comment]
Did you use FFmpeg CLI for Android?

The repository is here, https://github.com/magiclen/FFmpeg-CLI-For-Android

If you want FFmpeg CLI for Android to support x264, please use customized FFmpeg
