### ISSUE TITLE
Error splitting the argument list: Option not found

### ISSUE THREAD

**Issue by aikongmeng** [magiclen/FFmpeg-For-MagicLen-Applications#2]
我下載了 FFmpeg-For-MagicLen-Applications-3.0.2的 ffMpeg源代碼,
和您提供的配置文件,build_arm.sh 在修改了NDK路徑之後, 成功編譯出了arm 和arm_neon 文件夾的libffmpeg.so,但是我在執行libffmpeg.so的時候,提示我如下信息:

``` java
Welcome to my website:
https://magiclen.org
Error splitting the argument list: Option not found
```

我開始以為是編譯so文件的問題,所以我直接使用您編譯的[libffmpeg_arm.so](https://github.com/magiclen/FFmpeg-For-MagicLen-Applications/releases)
同樣的提示. 

另外,
我執行的命令是 /data/data/... libffmpeg.so -version .
我使用您編譯的ffmpeg 2.3 的so文件,是可以成功執行命令行的.
我想使用最新版本的ffmpeg, 我的源代碼[MainActivity](https://github.com/aikongmeng/GithubFFmpegTest/blob/master/magiclenDemo/src/main/java/com/example/magiclen/MainActivity.java)

期待您的回復.

**Comment by magiclen** [comment]
FFmpeg-For-MagicLen-Applications是我自行修改官方FFmpeg原始碼，使其能適用於我開發的應用程式，基於LGPL授權進行再開源的專案。如果您也要用FFmpeg進行開發，建議使用官方的FFmpeg原始碼哦！已經有比3.0.2更新的版本了～

**Comment by aikongmeng** [comment]
ffmpeg源碼編譯的so,我也嘗試了.  command running不執行,不報任何報錯 . 
源碼好像是不能使用ffmpeg command line,是這樣嗎? 
我想運行命令行也需要修改ffmpeg原始碼才可以嗎?

**Comment by magiclen** [comment]
官方的FFmpeg原始碼原本就有設計CLI，且可以成功完成Android交叉編譯。

**Comment by aikongmeng** [comment]
ffmpeg 3.1.1執行成功.
Tks,that's very nice of you!

**Comment by magiclen** [comment]
You're welcome.
