### ISSUE TITLE
failed with custom ffmpeg

### ISSUE THREAD

**Issue by andrii-dymov** [magiclen/FFmpeg-For-MagicLen-Applications#3]
I've added custom ffmpeg build and got the following error, which is obviously related to the apk:

Unrecognized option 'magiclen.org'.
Error splitting the argument list: Option not found

**Comment by magiclen** [comment]
You need to use this repo to compile for your custom ffmpeg.

https://github.com/magiclen/FFmpeg-For-MagicLen-Applications
