### ISSUE TITLE
如何編譯出 libffmpeg_arm64.so

### ISSUE THREAD

**Issue by charles1018** [magiclen/FFmpeg-For-MagicLen-Applications#5]
大神你好我有購買你的專業版因為我想要增加 x264 x265等功能,
按照你的How to Compile FFmpeg有成功編譯出來,
 libavcodec.a ibavfilter.a libavutil.a libswscale.alibavdevice.a libavformat.a libswresample.a
這幾個檔,
請問我要如何將這些檔案打包成 libffmpeg_arm64.so 作為客製化的二進制檔案自己使用,
下面是我的編譯腳本希望大神能指引一些步驟方向,
謝謝

> 

#!/bin/bash
NDK=/home/charles1018/Android/Sdk/ndk-bundle
SYSROOT=$NDK/platforms/android-21/arch-arm64
TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
NDK_TOOLCHAIN_ABI="aarch64-linux-android"
CROSS_PREFIX=${TOOLCHAIN}/bin/${NDK_TOOLCHAIN_ABI}-
export CC="${CROSS_PREFIX}21clang"
export CXX="${CROSS_PREFIX}21clang++"
export CPP="${CROSS_PREFIX}cpp"
export LD="${CROSS_PREFIX}ld"
export CCLD="${CROSS_PREFIX}ld "
export CXXLD="${CROSS_PREFIX}ld"
export RANLIB="${CROSS_PREFIX}ranlib"
export STRIP="${CROSS_PREFIX}strip"
export READELF="${CROSS_PREFIX}readelf"
export OBJDUMP="${CROSS_PREFIX}objdump"
export ADDR2LINE="${CROSS_PREFIX}addr2line"
export AR="${CROSS_PREFIX}ar"
export AS="${CROSS_PREFIX}clang"
export OBJCOPY="${CROSS_PREFIX}objcopy"
export ELFEDIT="${CROSS_PREFIX}elfedit"
export DWP="${CROSS_PREFIX}dwp"
export GCONV="${CROSS_PREFIX}gconv"
export GDP="${CROSS_PREFIX}gdb"
export GPROF="${CROSS_PREFIX}gprof"
export NM="${CROSS_PREFIX}nm"
export SIZE="${CROSS_PREFIX}size"
export STRINGS="${CROSS_PREFIX}strings"
build_android()
{
./configure \
--prefix=$(pwd)/android/armv8-a
--enable-static \
--disable-doc \
--disable-ffplay \
--disable-ffprobe \
--cross-prefix="${CROSS_PREFIX}" \
--target-os=android \
--arch=arm64 \
--enable-cross-compile \
--sysroot="${SYSROOT}" \
--cc=${CC} \
--cxx=${CXX} \
--as=${AS} \
--extra-ldflags="-fPIE -pie" \
--extra-libs="-lopus -lm" \
--pkg-config="$(which pkg-config)" \
--disable-debug \
--disable-shared \
--enable-gpl \
--enable-x264 \
--enable-x265 \
--enable-libvpx \
--enable-libass \
--enable-libopus \
--enable-libmp3lame \
--enable-libvidstab \
--enable-libxvid \
--enable-hardcoded-tables \
--enable-pic \
--enable-version3 \
--enable-pthreads \
make -j4
make install
}
build_android

**Comment by magiclen** [comment]
FFmpeg CLI Professional for Android只是應用戶要求推出的FFmpeg CLI for Android的去廣告版。由於x264 x265是GPL授權，無法直接跟著閉源的FFmpeg CLI for Android  一起被發布。所以用戶不管怎麼樣都要自行使用客製的FFMPEG。

關於編譯，請參考 How to Compile FFmpeg.md 文件

**Comment by magiclen** [comment]
FFmpeg CLI Professional for Android只是應用戶要求推出的FFmpeg CLI for Android的去廣告版。由於x264 x265是GPL授權，無法直接跟著閉源的FFmpeg CLI for Android  一起被發布。所以用戶不管怎麼樣都要自行使用客製的FFMPEG。

關於編譯，參考 How to Compile FFmpeg.md 文件編譯出來的是FFmpeg的執行檔(無動態函式庫相依)，只要把執行檔命名為libxxxx.so丟進Android程式專案(假設你是在開發Android程式)來用就好

**Comment by charles1018** [comment]
感謝說明我後來把編譯出來的執行檔重新命名為libxxxx.so後，已經可以正常使用，網路上編譯android執行檔的文章大都是用舊的gcc編譯方式，你的文件讓新手關於編譯這一塊可以很快上手，謝謝。
