### ISSUE TITLE
作者你好！你可不可以再额外编译一个arm静态连接版本的ffmpeg二进制程序？

### ISSUE THREAD

**Issue by cDQK** [magiclen/FFmpeg-For-MagicLen-Applications#6]
如题，感觉APP版本不如命令行的好用

**Comment by magiclen** [comment]
請問是要給Linux on ARM使用的嗎？

APP版本是指？

**Comment by cDQK** [comment]
@magiclen 哦不是，我是想在安卓的终端模拟器上使用的。那个app版本就是你的那个｀fffmpeg命令列｀软件，我觉得它的安装包安装后太大了，加上它没有相对路径的，输出文件老是要复制路径不方便😊

**Comment by magiclen** [comment]
如果是這樣的話，release分頁已經有放Android on ARM的二進制執行檔了，副檔名.so是為了包進apk才用的，它實際上不是shared object file

**Comment by cDQK** [comment]
@magiclen 可是我试着把它放到终端模拟器运行后无论后面输入的是什么都是提示：
【WARNING: linker: ./ffmpeg_4: unused DT entry: type 0x6ffffffe arg 0x3a54
WARNING: linker: ./ffmpeg_4: unused DT entry: type 0x6fffffff arg 0x4
ffmpeg version 4.1.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with Android (5058415 based on r339409) clang version 8.0.2 (https://android.googlesource.com/toolchain/clang 40173bab62ec746213857d083c0e8b0abb568790) (https://android.googlesource.com/toolchain/llvm 7a6618d69e7e8111e1d49dc9e7813767c5ca756a) (based on LLVM 8.0.2svn)
 Builder magiclen.org
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100


Welcome to my website:

https://magiclen.org

Error splitting the argument list: Option not found】
这好像切实是不能运行的？

**Comment by magiclen** [comment]
參數要加上`-magiclen.org`

**Comment by cDQK** [comment]
@magiclen  确实能运行了，谢谢！
